include $(PROJECT_PATH)/libdglGauges/dglRenderWrapper/dglRenderWrapper.mk
include $(PROJECT_PATH)/libdglGauges/dglGaugesGeometry/dglGaugesGeometry.mk
include $(PROJECT_PATH)/libdglGauges/dglGaugesBase/dglGaugesBase.mk
include $(PROJECT_PATH)/libdglGauges/dglGaugesInstruments1/dglGaugesInstruments1.mk

DGLGAUGES_OBJECTS= $(DGLGAUGESBASE_COMPONENT_OBJ) \
					$(DGLGAUGESGEOMETRY_COMPONENT_OBJ) \
					$(DGLRENDERWRAPPER_COMPONENT_OBJ) \
					$(DGLGAUGESINSTRUMENTS1_COMPONENT_OBJ)

DGLGAUGES_OUTPUT_FOLDERS = $(DGLGAUGESBASE_COMPONENT_OUTPUT_FOLDER) \
						$(DGLGAUGESGEOMETRY_COMPONENT_OUTPUT_FOLDER) \
						$(DGLRENDERWRAPPER_COMPONENT_OUTPUT_FOLDER) \
						$(DGLGAUGESINSTRUMENTS1_COMPONENT_OUTPUT_FOLDER)

dglGaugesClean:
	rm -rf \
	$(DGLGAUGESBASE_COMPONENT_OUTPUT_FOLDER) \
	$(DGLGAUGESGEOMETRY_COMPONENT_OUTPUT_FOLDER) \
	$(DGLGAUGESINSTRUMENTS1_COMPONENT_OUTPUT_FOLDER) \
	$(DGLRENDERWRAPPER_COMPONENT_OUTPUT_FOLDER)
	
dglGaugesCompile: $(DGLGAUGES_OBJECTS)