include $(PROJECT_PATH)/lib/dglGaugesGeometry/dglGaugesGeometry.mk
include $(PROJECT_PATH)/lib/dglGaugesBase/dglGaugesBase.mk
include $(PROJECT_PATH)/lib/dglGaugesInstruments1/dglGaugesInstruments1.mk
include $(PROJECT_PATH)/lib/dglGaugesInstruments2/dglGaugesInstruments2.mk

DGLGAUGES_OBJECTS= $(DGLGAUGESBASE_COMPONENT_OBJ) \
					$(DGLGAUGESGEOMETRY_COMPONENT_OBJ) \
					$(DGLGAUGESINSTRUMENTS1_COMPONENT_OBJ)\
					$(DGLGAUGESINSTRUMENTS2_COMPONENT_OBJ)\

DGLGAUGES_OUTPUT_FOLDERS = $(DGLGAUGESBASE_COMPONENT_OUTPUT_FOLDER) \
						$(DGLGAUGESGEOMETRY_COMPONENT_OUTPUT_FOLDER) \
						$(DGLGAUGESINSTRUMENTS1_COMPONENT_OUTPUT_FOLDER)\
						$(DGLGAUGESINSTRUMENTS2_COMPONENT_OUTPUT_FOLDER)\

DGLGAUGES_INCLUDES=	$(DGLGAUGESBASE_COMPONENT_INCLUDES)\
					$(DGLGAUGESGEOMETRY_COMPONENT_INCLUDES)\
					$(DGLGAUGESINSTRUMENTS1_COMPONENT_INCLUDES)\
					$(DGLGAUGESINSTRUMENTS2_COMPONENT_INCLUDES)\


dglGaugesClean:
	rm -rf \
	$(DGLGAUGESBASE_COMPONENT_OUTPUT_FOLDER) \
	$(DGLGAUGESINSTRUMENTS1_COMPONENT_OUTPUT_FOLDER) \
	$(DGLGAUGESINSTRUMENTS2_COMPONENT_OUTPUT_FOLDER) \
	
dglGaugesCompile: $(DGLGAUGES_OBJECTS)